project:
  type: website
  output-dir: docs

website:
  title: "time4stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: slides.qmd
        text: Materials

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

